database:
  url: "host=localhost port=5432 user=postgres dbname=candidates password=postgres sslmode=disable"
  name: "test.db"
  user: "admin"
  password: "admin"
  dialect: "postgres"
  mongoURL: "mongo url"


server:
  host: "host name"
  port: 8080
